"""alter users table create user_roles

Revision ID: 37eef88890fb
Revises: 0911b4db9c73
Create Date: 2026-05-14 19:04:10.104616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '37eef88890fb'
down_revision: Union[str, Sequence[str], None] = '0911b4db9c73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_roles',
                    sa.Column('user_id', sa.Uuid(), nullable=False),
                    sa.Column('company_id', sa.Uuid(), nullable=False),
                    sa.Column('role',
                              sa.Enum('admin', 'director', 'technical_director', 'senior_technician', 'technician',
                                      'storekeeper', 'viewer', name='role'), nullable=False),
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                              nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                              nullable=False),
                    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('user_id', 'company_id', 'role', name='uq_user_company_role')
                    )
    op.create_index(op.f('ix_user_roles_company_id'), 'user_roles', ['company_id'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.add_column('users', sa.Column('active_company_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'users', 'companies', ['active_company_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'active_company_id')
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_company_id'), table_name='user_roles')
    op.drop_table('user_roles')
    # ### end Alembic commands ###
